/**
 * secrets.yaml 读写模块 - 存储 Wise DevOps 凭据（cookie + x-csrf-token）
 *
 * 存储位置：server/data/secrets.yaml
 * 格式：
 *   cookie: "..."
 *   x_csrf_token: "..."
 *   source: "manual" | "wise-login"
 *   updated_at: "2026-08-08 10:00:00"
 *
 * 实现极简 YAML 序列化（本项目只需处理字符串键值对，不引入 yaml 依赖），
 * 保证与文档中 Python 引擎 secrets.yaml 的格式兼容。
 */
const fs = require('fs');
const path = require('path');
const { logger } = require('./logger');

const DATA_DIR = path.join(__dirname, '..', 'data');
const SECRETS_FILE = path.join(DATA_DIR, 'secrets.yaml');

function ensureDir() {
  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
}

/** 简单 YAML 字符串转义：仅需保证双引号字符串安全 */
function yamlQuote(value) {
  const s = String(value == null ? '' : value);
  // 含特殊字符时用双引号包裹并转义内部双引号
  if (/[:#"'\n\r\\]/.test(s)) {
    return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r') + '"';
  }
  return s;
}

/** 极简 YAML 解析：只支持 `key: value`（value 可为裸值或双引号字符串） */
function yamlParse(content) {
  const result = {};
  for (const rawLine of String(content).split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (value.startsWith('"') && value.endsWith('"') && value.length >= 2) {
      value = value.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\').replace(/\\n/g, '\n').replace(/\\r/g, '\r');
    }
    result[key] = value;
  }
  return result;
}

/** 读取凭据，不存在时返回空对象 */
function readSecrets() {
  ensureDir();
  if (!fs.existsSync(SECRETS_FILE)) return {};
  try {
    return yamlParse(fs.readFileSync(SECRETS_FILE, 'utf-8'));
  } catch (e) {
    logger.error('[secrets] read failed', e);
    return {};
  }
}

/** 写入凭据 */
function writeSecrets(fields) {
  ensureDir();
  const lines = ['# Wise DevOps credentials, generated by service inspection system'];
  for (const [key, value] of Object.entries(fields)) {
    lines.push(`${key}: ${yamlQuote(value)}`);
  }
  try {
    fs.writeFileSync(SECRETS_FILE, lines.join('\n') + '\n', 'utf-8');
    logger.info('[secrets] written');
  } catch (e) {
    logger.error('[secrets] write failed', e);
    throw e;
  }
}

function formatTime(date = new Date()) {
  const p = (n) => String(n).padStart(2, '0');
  return `${date.getFullYear()}-${p(date.getMonth() + 1)}-${p(date.getDate())} ${p(date.getHours())}:${p(date.getMinutes())}:${p(date.getSeconds())}`;
}

/** 保存凭据（cookie + csrf），记录来源与时间 */
function saveSecrets({ cookie, xCsrfToken, source }) {
  writeSecrets({
    cookie: cookie || '',
    x_csrf_token: xCsrfToken || '',
    source: source || 'manual',
    updated_at: formatTime()
  });
  logger.info(`[secrets] saved source=${source} cookieLen=${String(cookie || '').length} csrfLen=${String(xCsrfToken || '').length}`);
}

/** 凭据状态：是否已配置 + 预览（脱敏） */
function getStatus() {
  const s = readSecrets();
  const configured = Boolean(s.cookie && s.x_csrf_token);
  return {
    configured,
    source: s.source || '',
    updatedAt: s.updated_at || '',
    cookiePreview: s.cookie ? s.cookie.slice(0, 12) + '...' : '',
    csrfPreview: s.x_csrf_token ? s.x_csrf_token.slice(0, 6) + '...' : ''
  };
}

/** 供巡检请求使用：返回完整凭据（cookie + x-csrf-token） */
function getCredentialPair() {
  const s = readSecrets();
  return { cookie: s.cookie || '', xCsrfToken: s.x_csrf_token || '' };
}

module.exports = { readSecrets, saveSecrets, getStatus, getCredentialPair, SECRETS_FILE };
